### ISSUE TITLE
Group Messaging

### ISSUE THREAD

**Issue by trevorbonas** [CMPT362-Messaging/Concord-Messenger#5]
The user should be able to create a messaging group by picking other users from their friends list. The user should also be able to be added to messaging groups by other users. The user should also be able to leave groups they have joined and delete groups they have created. All messages sent in messaging groups should be sent to all users in the group.

**Comment by dylanbingmanners** [comment]
[#](https://github.com/CMPT362-Messaging/Concord-Messenger/commit/de8d93ddc85da72c9608d92ee96a654fc52522ef)
